export const images = [
    {
        index: 1,
        src: '/fourdogs.webp',
        width: 1792,
        height: 1024,
        thumbnail: ''
    },
    {
        src: '/golden1.webp',
        original: '/golden1.webp',
        width: 1792,
        height: 1024,
        index: 2,
        alt: 'gallery image',  thumbnail: ''
    },
    {
        src: '/golden_forest.jpg',
        original: '/golden_forest.jpg',
        width: 512,
        height: 512,
        index: 3,
        alt: 'gallery image',  thumbnail: ''
    },
    {
        src: '/fourdogs.webp',
        original: '/fourddogs.webp',
        width: 1344,
        height: 768,
        index: 4,
        alt: 'gallery image',
    },
    {
        src: '/spaniel.jpg',
        original: '/spaniel.jpgp',
        width: 512,
        height: 384,
        index: 5,
        alt: 'gallery image',
    },
    {
        src: '/fourdogs.webp',
        original: '/fourddogs.webp',
        width: 1344,
        height: 768,
        index: 6,
        alt: 'gallery image',
    },
    {
        src: '/golden1.webp',
        original: '/golden1.webp',
        width: 1792,
        height: 1024,
        index: 7,
        alt: 'gallery image',
    },
    {
        src: '/golden_forest.jpg',
        original: '/golden_forest.jpg',
        width: 512,
        height: 512,
        index: 8,
        alt: 'gallery image',
    },
    {
        src: '/portrait2.webp',
        original: '/portrait2.webp',
        width: 366,
        height: 640,
        index: 9,
        alt: 'gallery image',
    },
    {
        src: '/svetovno_iskanje.jpg',
        original: '/svetovno_iskanje.jpg',
        width: 480,
        height: 320,
        index: 10,
        alt: 'gallery image',
    },
    {
        src: '/portrait2.webp',
        original: '/portrait2.webp',
        width: 366,
        height: 640,
        index: 11,
        alt: 'gallery image',
    },

    {
        src: '/svetovno_iskanje.jpg',
        original: '/svetovno_iskanje.jpg',
        width: 6400,
        height: 3600,
        index: 12,
        alt: 'gallery image',
    },
    {
        src: '/golden1.webp',
        original: '/golden1.webp',
        width: 320,
        height: 180,
        index: 13,
        alt: 'gallery image',
    },
    {
        src: '/portrait2.webp',
        original: '/portrait2.webp',
        width: 180,
        height: 320,
        index: 14,
        alt: 'gallery image',
    },
    {
        src: '/golden_forest.jpg',
        original: '/golden_forest.jpg',
        width: 320,
        height: 180,
        index: 15,
        alt: 'gallery image',
    },
]
